export { default as HomePage } from './HomePage/HomePage.jsx'
export { default as LoginPage } from './LoginPage/LoginPage.jsx'
// export { default as RegisterPage } from './RegisterPage/RegisterPage.jsx'
// export { default as ArticlePage } from './ArticlePage/ArticlePage.jsx'
// export { default as ArticlesPage } from './ArticlesPage/ArticlesPage.jsx'
// export { default as WritePage } from './WritePage/WritePage.jsx'
// export { default as CorpusPage } from './CorpusPage/CorpusPage.jsx'
// export { default as WorkspacePage } from './WorkspacePage/WorkspacePage.jsx'
// export { default as CredentialsPage } from './CredentialsPage/CredentialsPage.jsx'
// export { default as PrivacyPage } from './PrivacyPage/PrivacyPage.jsx'
// export { default as ExportPage } from './ExportPage/ExportPage.jsx'